config/routes.rb
BhsSms::Application.routes.draw do
  get "parents/modify"

  get "parents/list"

  get "users/list"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "students/list"
  post "students/new"

  get "instruments/list"
  get "uniforms/list"
  get "languages/list"

  resources :students do
    resources :parents
  end

  resources :uniforms
  resources :instruments
  resources :languages

  root to: 'sessions#new'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "roles/modify"

  get "roles/show"

  get "uniform_damage/modify"












end

app/models/language.rb
# == Schema Information
#
# Table name: languages
#
#  id         :integer         not null, primary key
#  name       :string(255)
#  abbr       :string(255)
#  available  :boolean
#  created_at :datetime        not null
#  updated_at :datetime        not null
#

class Language < ActiveRecord::Base
end

app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  helper_method :sort_column

   def new
     @language = Language.new
     @language.available = true
     @method = "Add"
     render 'modify'
   end

   def create
     @language = Language.new(params[:language])
     if @language.save
       flash[:success] = "Added Language."
       redirect_to "/languages/list"
     else
       @method = "Add"
       render 'modify'
     end
   end

   def edit
     @language = Language.find(params[:id])
     @method = "Edit"
     render 'modify'
   end

   def update
     @language = Language.find(params[:id])
     if @language.update_attributes(params[:language])
       flash[:success] = "Updated Language."
       redirect_to "/languages/list"
     else
       @method = "Edit"
       render 'modify'
     end
   end

   def destroy
     @language = Language.find(params[:id])
     user = @language.student_id
     if user.nil? || Student.find(user).nil?
       @language.destroy
     else
       user = Student.find(user)
       user.language.destroy
     end
     flash[:success] = "Deleted Language."
     redirect_to "/languages/list"
   end

   def list

   end


   private
   def sort_column
     Language.column_names.include?(params[:sort]) ? params[:sort] : "name"
   end

end

app/helpers/languages_helper.rb
module LanguagesHelper
end

app/views/languages/list.html.erb
<% provide(:title, "List Languages") %>
<h1>List Languages</h1>
<%= link_to "Create New language", new_language_path %> <br/><br/>
<i>Here are all of the languages:</i><br/><br/>
<table class="list">
  <tr>
    <th><%= sortable "name", "Language" %></th>
    <th><%= sortable "abbr", "Language Abbreviation" %></th>
    <th><%= sortable "available", "Language is Available" %></th>
    <th>Edit Language</th>
    <th>Delete Language</th>
  </tr>

  <% Language.order(sort_column + ' ' + sort_direction).each do |language| %>
      <tr>
        <td><%= language.name %></td>
        <td><%= language.abbr %></td>
        <td><%= language.available %></td>
        <td><%= link_to "Edit", edit_language_path(language) %></td>
        <td><%= link_to "Delete", language_path(language), method: :delete, confirm: "Are you sure you want to delete this language? This action cannot be undone." %></td>
      </tr>
  <% end %>
</table>

app/views/languages/modify.html.erb
<% provide(:title, @method + " Language") %>
<h1><%= @method + " Language" %></h1>
<i>Complete the form to <%= @method.downcase %> a language.</i><br/><br/>

<%= render 'shared/error_messages', :object => @language %>

<%= form_for(@language) do |f| %>

    <h3>Language Information:</h3>

    <table class="form_table">
      <tr>
        <td><%= f.label :name, "Language Name" %>:</td>
        <td><%= f.text_field :name %></td>
      </tr>

      <tr>
        <td><%= f.label :abbr, "Language Abbreviation" %>:</td>
        <td><%= f.text_field :abbr %></td>
      </tr>

      <tr>
        <td><%= f.check_box :available %></td>
        <td><%= f.label :available, "Language is available" %></td>
      </tr>
    </table><br/><br/>

    <i>Assign a parent a language through the student panel.</i><br/><br/>

    <%= f.submit @method + " Language", style: "width: 170px; height: 30px;" %>
<% end %>