config/routes.rb
BhsSms::Application.routes.draw do
  get "parents/modify"

  get "parents/list"

  get "users/list"

  resources :users
  resources :sessions, only: [:new, :create, :destroy]

  get "students/list"
  post "students/new"

  get "instruments/list"
  get "uniforms/list"
  get "languages/list"

  resources :students do
    resources :parents
  end

  resources :uniforms
  resources :instruments
  resources :languages

  root to: 'sessions#new'

  match '/signup', to: 'users#new'
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy', via: :delete

  get "roles/modify"

  get "roles/show"

  get "uniform_damage/modify"












end

app/models/instrument.rb
# == Schema Information
#
# Table name: instruments
#
#  id                :integer         not null, primary key
#  student_id        :integer
#  instrument        :string(255)
#  instrument_number :string(255)
#  description       :string(255)
#  created_at        :datetime        not null
#  updated_at        :datetime        not null
#

class Instrument < ActiveRecord::Base
  belongs_to :student
end

app/controllers/instruments_controller.rb
class InstrumentsController < ApplicationController

  helper_method :sort_column

  def new
    @instrument = Instrument.new
    @method = "Add"
    render 'modify'
  end

  def create
    @instrument = Instrument.new(params[:instrument])
    if @instrument.save
      flash[:success] = "Added Instrument."
      redirect_to "/instruments/list"
    else
      @method = "Add"
      render 'modify'
    end
  end

  def edit
    @instrument = Instrument.find(params[:id])
    @method = "Edit"
    render 'modify'
  end

  def update
    @instrument = Instrument.find(params[:id])
    if @instrument.update_attributes(params[:instrument])
      flash[:success] = "Updated Instrument."
      redirect_to "/instruments/list"
    else
      @method = "Edit"
      render 'modify'
    end
  end

  def destroy
    @instrument = Instrument.find(params[:id])
    user = @instrument.student_id
    if user.nil? || Student.find(user).nil?
      @instrument.destroy
    else
      user = Student.find(user)
      user.instrument.destroy
    end
    flash[:success] = "Deleted Instrument."
    redirect_to "/instruments/list"
  end

  def list

  end


  private
  def sort_column
    Instrument.column_names.include?(params[:sort]) ? params[:sort] : "instrument"
  end

end

app/helpers/instruments_helper.rb
module InstrumentsHelper
end

app/views/instruments/list.html.erb
<% provide(:title, "List Instruments") %>
<h1>List Instruments</h1>
<%= link_to "Create New instrument", new_instrument_path %> <br/><br/>
<i>Here are all of the instruments:</i><br/><br/>
<table class="list">
  <tr>
    <th><%= sortable "instrument", "Instrument Type" %></th>
    <th><%= sortable "instrument_number" %></th>
    <th><%= sortable "description" %></th>
    <th><%= sortable "student_id", "Current Student" %></th>
    <th>Edit Instrument</th>
    <th>Delete Instrument</th>
  </tr>

  <% Instrument.order(sort_column + ' ' + sort_direction).each do |instrument| %>
      <tr>
        <% if !instrument.student_id.nil? then student = Student.find(instrument.student_id) else student = nil end %>
        <td><%= instrument.instrument %></td>
        <td><%= instrument.instrument_number.to_s %></td>
        <td><%= instrument.description %></td>
        <td><%= if !student.nil? then student.first_name + " " + student.last_name else "No Student Assigned" end %></td>
        <td><%= link_to "Edit", edit_instrument_path(instrument) %></td>
        <td><%= link_to "Delete", instrument_path(instrument), method: :delete, confirm: "Are you sure you want to delete this instrument? This action cannot be undone." %></td>
      </tr>
  <% end %>
</table>

app/views/instruments/modify.html.erb
<% provide(:title, @method + " Instrument") %>
<h1><%= @method + " Instrument" %></h1>
<i>Complete the form to <%= @method.downcase %> an instrument.</i><br/><br/>

<%= render 'shared/error_messages', :object => @instrument %>

<%= form_for(@instrument) do |f| %>

    <h3>Instrument Information:</h3>

    <table class="form_table">
      <tr>
        <td><%= f.label :instrument, "Instrument Type" %>:</td>
        <td><%= f.text_field :instrument %></td>
      </tr>

      <tr>
        <td><%= f.label :instrument_number %>:</td>
        <td><%= f.text_field :instrument_number %></td>
      </tr>

      <tr>
        <td><%= f.label :description, "Description (Including Damages)" %>:</td>
        <td><%= f.text_field :description %></td>
      </tr>
    </table><br/><br/>

    <i>Assign a student an instrument through the student panel.</i><br/><br/>

    <%= f.submit @method + " Instrument", style: "width: 170px; height: 30px;" %>
<% end %>